services:
  app:
    build:
      context: ./server
    ports:
      - "5050:5050"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ai-doctor-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-doctor-network

networks:
  ai-doctor-network:
    driver: bridge

volumes:
  ollama_data:
