import React, { useState, useEffect, useRef, useMemo } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import api from "../utils/api";
import LegalModal from "../components/LegalModal";
import MessageText from "../components/MessageText";
import { getUserId } from "../utils/user";
import { sendChatStream } from "../utils/chatStream";
import { loadReportDigest } from "../utils/reportContext";
import { isMemoryEnabled } from "../utils/healthMemory";
import { useAuth } from "../context/AuthContext";
import { useFeedback } from "../context/FeedbackContext";
import { findSpecialist } from "../data/specialists";
import { ArrowLeft, Camera, Check, Close, Refresh, Send, Shield, Spinner, Stethoscope, ThumbDown, ThumbUp } from "../components/Icons";

const CONSENT_KEY = "chat_consent";

// Older stored replies end with a block of safety and status lines the server
// used to append. Everything from the first of those lines on is left out.
const TRAILER_EXACT = new Set(["SAFETY OVERSIGHT SYSTEM", "MEDICAL LEGAL DISCLAIMER", "[ EXECUTE ]", "ACCURATE?"]);
const TRAILER_PREFIXES = [
  "VERIFIED SOURCES", "LATENCY:", "UPTIME:", "MEDNEXUS v", "BUILD:", "CORE:", "IDENTITY:",
  "SECURE LINK ESTABLISHED", "NEURAL LINK ACTIVE",
  "This response is generated by an AI assistant",
  "It is NOT a substitute for professional medical advice",
  "Always seek the advice of your physician",
  "Always consult a physician",
  "Never disregard professional medical advice",
  "IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY",
];

const sanitizeMessageText = (text = "") => {
  const cleaned = [];
  for (const line of String(text).split(/\r?\n/)) {
    const trimmed = line.trim();
    // Stored headings may start with a symbol; compare from the first letter or bracket
    const plain = trimmed.replace(/^[^A-Za-z[]+/, "");
    if (
      /^━+$/.test(trimmed) ||
      /^-{3,}$/.test(trimmed) ||
      TRAILER_EXACT.has(plain) ||
      TRAILER_PREFIXES.some((prefix) => plain.startsWith(prefix))
    ) break;
    cleaned.push(line);
  }
  return cleaned.join("\n").replace(/\n{3,}/g, "\n\n").trim();
};

const ERROR_TEXT = {
  SESSION_COMPLETE: "This consultation is finished. Start a new one to continue.",
  REVIEW_PENDING: "Your assessment is with a clinician. It will appear here once it is approved.",
  IMAGE_LIMIT_REACHED: "Only one photo can be sent in a consultation.",
  ASSISTANT_UNAVAILABLE: "The assistant is temporarily unavailable. Please try again shortly. In an emergency, call your local emergency number.",
};

export default function Chatbot() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [image, setImage] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [isTyping, setIsTyping] = useState(false);
  const [stepLabel, setStepLabel] = useState("");
  const [pendingReview, setPendingReview] = useState(false);
  const [sessionClosed, setSessionClosed] = useState(false);
  const [followUpState, setFollowUpState] = useState("idle"); // idle | saving | scheduled | failed
  const [error, setError] = useState(null);
  const [historyLoaded, setHistoryLoaded] = useState(false);
  const [hasConsented, setHasConsented] = useState(() => sessionStorage.getItem(CONSENT_KEY) === "yes");
  const [isLegalOpen, setIsLegalOpen] = useState(false);
  const listRef = useRef(null);
  const fileInputRef = useRef(null);
  const inputRef = useRef(null);
  const { user, checkTokenLimit, consumeTokens, tokenUsage, usageLimit } = useAuth();
  const { toast, confirm } = useFeedback();
  const location = useLocation();
  const navigate = useNavigate();
  const { specialization } = useParams();

  // The specialist comes from the page that linked here, or from the address
  const activeDoctor = useMemo(() => {
    const name = location.state?.specializationName || specialization || "General Physician";
    return { name, role: location.state?.specializationRole || findSpecialist(name)?.role || "Specialist" };
  }, [location.state?.specializationName, location.state?.specializationRole, specialization]);
  const isPremium = location.state?.tier === "premium";
  const historyUrl = `/api/chat/history/${getUserId()}/${encodeURIComponent(activeDoctor.name)}`;

  // Keep the latest message in view
  useEffect(() => {
    const list = listRef.current;
    if (list) list.scrollTo({ top: list.scrollHeight, behavior: "smooth" });
  }, [messages, isTyping, pendingReview, sessionClosed, historyLoaded]);

  // Load the earlier messages of this consultation once the user has agreed to the terms
  useEffect(() => {
    if (!hasConsented) return;
    setHistoryLoaded(false);
    api.get(historyUrl)
      .then((res) => {
        setPendingReview(!!res.data.pendingReview);
        setSessionClosed(!!res.data.sessionClosed);
        setMessages(res.data.messages || []);
      })
      .catch((err) => {
        console.error("Failed to load history", err);
        setError("Earlier messages could not be loaded.");
      })
      .finally(() => setHistoryLoaded(true));
  }, [historyUrl, hasConsented]);

  // A message handed over by another page (a report, or a check-in) is put in
  // the input box; the user still decides whether to send it.
  useEffect(() => {
    if (location.state?.initialMessage) setInput(location.state.initialMessage);
  }, [location.state?.initialMessage]);

  // While a clinician has the draft, look for the released assessment.
  useEffect(() => {
    if (!pendingReview) return undefined;
    const timer = setInterval(() => {
      api.get(historyUrl)
        .then((res) => {
          if (!res.data.pendingReview) {
            setMessages(res.data.messages || []);
            setSessionClosed(!!res.data.sessionClosed);
            setPendingReview(false);
          }
        })
        .catch(() => { });
    }, 15000);
    return () => clearInterval(timer);
  }, [pendingReview, historyUrl]);

  const giveConsent = () => {
    sessionStorage.setItem(CONSENT_KEY, "yes");
    setHasConsented(true);
  };

  const requestFollowUp = async () => {
    setFollowUpState("saving");
    try {
      await api.post("/api/followup", {
        userId: getUserId(),
        specialization: activeDoctor.name,
        email: user?.email,
        days: 2
      });
      setFollowUpState("scheduled");
      toast(`Check-in scheduled. We will email ${user?.email} in 2 days.`);
    } catch (err) {
      console.warn("Check-in could not be scheduled", err);
      setFollowUpState("failed");
    }
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImage(file);
      setImagePreview(URL.createObjectURL(file));
      setError(null);
    }
    e.target.value = ""; // lets the same file be picked again after it is removed
  };

  const removeImage = () => {
    setImage(null);
    setImagePreview(null);
  };

  const sendMessage = async () => {
    if (isTyping || (!input.trim() && !image)) return;

    // Usage is counted in characters; a photo counts as 500
    const usageCost = input.length + (image ? 500 : 0);

    if (!checkTokenLimit(usageCost)) {
      setError(user?.isGuest
        ? "You have reached today's guest limit. Sign in to continue, or come back tomorrow."
        : "You have reached the usage limit for this account.");
      return;
    }

    setMessages((prev) => [...prev, { sender: "user", text: input, image: imagePreview }]);

    const formData = new FormData();
    formData.append("message", input);
    formData.append("specialization", activeDoctor.name);
    formData.append("userId", getUserId());
    formData.append("tier", isPremium ? "premium" : "basic");
    if (image) formData.append("image", image);
    formData.append("memory", isMemoryEnabled() ? "on" : "off");
    const reportDigest = loadReportDigest();
    if (reportDigest) formData.append("reportSummary", reportDigest);

    setInput("");
    removeImage();
    setIsTyping(true);
    setStepLabel("");
    setError(null);

    try {
      // Progress arrives as it happens; the reply arrives once it has passed the server's safety checks
      const data = await sendChatStream(formData, (step) => setStepLabel(step.label || ""));

      if (data.reply) {
        setMessages((prev) => [
          ...prev,
          { sender: "ai", text: data.reply, citations: data.citations || [], sessionComplete: !!data.sessionComplete }
        ]);
        consumeTokens(usageCost + data.reply.length);
        setPendingReview(!!data.pendingReview);
        if (data.sessionComplete) setSessionClosed(true);
      }
    } catch (err) {
      console.error("Chat error:", err);
      if (err.code === "SESSION_COMPLETE") setSessionClosed(true);
      if (err.code === "REVIEW_PENDING") setPendingReview(true);
      setError(ERROR_TEXT[err.code] || "The connection was interrupted. Please try again.");
    } finally {
      setIsTyping(false);
      setStepLabel("");
      inputRef.current?.focus();
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const handleFeedback = async (messageIndex, type) => {
    const message = messages[messageIndex];
    setMessages((prev) => prev.map((m, i) => (i === messageIndex ? { ...m, feedback: type } : m)));
    try {
      await api.post("/api/chat/feedback", {
        userId: getUserId(),
        messageText: message.text,
        type,
        specialization: activeDoctor.name
      });
    } catch (err) {
      console.warn("Feedback was not saved on the server.", err);
    }
  };

  // Ends the questions early and asks for the assessment now
  const finishConsultation = async () => {
    const agreed = await confirm({
      title: "Finish the consultation?",
      text: "The assistant stops asking questions and writes your summary now. After that this consultation is closed.",
      confirmLabel: "Get my summary",
    });
    if (!agreed) return;
    setIsTyping(true);
    setError(null);
    try {
      const res = await api.post("/api/chat/force-final", {
        userId: getUserId(),
        specialization: activeDoctor.name,
        tier: isPremium ? "premium" : "basic",
        memory: isMemoryEnabled() ? "on" : "off"
      });
      if (res.data.reply) {
        setMessages((prev) => [
          ...prev,
          { sender: "ai", text: res.data.reply, citations: res.data.citations || [], sessionComplete: !!res.data.sessionComplete }
        ]);
        consumeTokens(500); // fixed cost for a summary
      }
      setPendingReview(!!res.data.pendingReview);
      if (res.data.sessionComplete) setSessionClosed(true);
    } catch (err) {
      console.error("Summary error", err);
      const code = err.response?.data?.error;
      if (code === "REVIEW_PENDING") setPendingReview(true);
      setError(ERROR_TEXT[code] || "The summary could not be created. Please try again.");
    } finally {
      setIsTyping(false);
    }
  };

  // A finished consultation is locked; starting again clears it on the server
  const startNewConsultation = async () => {
    const agreed = await confirm({
      title: "Start a new consultation?",
      text: "The messages in this consultation will be deleted. This cannot be undone.",
      confirmLabel: "Delete and start new",
      tone: "danger",
    });
    if (!agreed) return;
    try {
      await api.delete(historyUrl);
      setMessages([]);
      setSessionClosed(false);
      setPendingReview(false);
      setFollowUpState("idle");
      setError(null);
    } catch (err) {
      console.error("Could not clear the consultation", err);
      setError("A new consultation could not be started. Please try again.");
    }
  };

  const userTurns = messages.filter((m) => m.sender === "user").length;
  const canFinish = userTurns >= 2 && !sessionClosed && !pendingReview && !isTyping;
  const canAskFollowUp = sessionClosed && !pendingReview && !isTyping && user?.email && !user?.isGuest;
  const usagePercent = Math.min(100, Math.round((tokenUsage / usageLimit) * 100));
  const SpecialistIcon = findSpecialist(activeDoctor.name)?.icon || Stethoscope;
  const status = sessionClosed ? { label: "Finished", tone: "text-muted" }
    : pendingReview ? { label: "With a clinician", tone: "text-warn" }
      : { label: "In progress", tone: "text-ok" };
  const context = [
    { label: "Reply mode", value: isPremium ? "Fast" : "Private" },
    { label: "Health memory", value: isMemoryEnabled() ? "On" : "Off", to: "/settings" },
    { label: "Lab report", value: loadReportDigest() ? "Included" : "None", to: "/report" },
  ];

  return (
    <div className="mx-auto flex h-[calc(100dvh-4rem)] w-full max-w-6xl gap-6 px-0 sm:px-8 sm:pb-6 sm:pt-2">

      {/* Conversation */}
      <div className="relative flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden border-line bg-surface shadow-soft sm:rounded-2xl sm:border">

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-line px-4 py-3">
          <button onClick={() => navigate("/consultation")} className="btn btn-ghost px-2" aria-label="Back to specialists">
            <ArrowLeft />
          </button>
          <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-brand-soft text-brand"><SpecialistIcon /></span>
          <div className="min-w-0 flex-1">
            <h1 className="truncate text-base font-semibold text-ink">{activeDoctor.name}</h1>
            <p className="truncate text-xs text-muted">{activeDoctor.role} · AI assistant, not a doctor</p>
          </div>
          {canFinish && (
            <button onClick={finishConsultation} className="btn btn-secondary fade-in shrink-0 px-3 py-2 text-xs xl:hidden">
              Finish and get summary
            </button>
          )}
        </div>

        {/* Messages */}
        <div ref={listRef} className="flex-1 space-y-4 overflow-y-auto px-4 py-5 sm:px-6" aria-live="polite">
          {hasConsented && !historyLoaded && (
            <div className="space-y-4" aria-label="Loading earlier messages">
              <div className="skeleton ml-auto h-10 w-2/5" />
              <div className="skeleton h-20 w-3/5" />
              <div className="skeleton ml-auto h-10 w-1/3" />
            </div>
          )}

          {historyLoaded && messages.length === 0 && (
            <div className="fade-in mx-auto max-w-md py-10 text-center">
              <span className="pulse-ring mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-brand-soft text-brand">
                <SpecialistIcon />
              </span>
              <p className="mt-4 text-base font-semibold text-ink">Tell me what is bothering you.</p>
              <p className="mt-1.5 text-sm leading-relaxed text-muted">
                I will ask a few questions, then give you a short summary with possible causes, self-care and when to see a doctor.
                You can also send one photo.
              </p>
            </div>
          )}

          {messages.map((msg, i) => {
            const isUser = msg.sender === "user";
            return (
              <div key={i} className={`message-in flex ${isUser ? "justify-end" : "justify-start"}`}>
                <div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${isUser
                  ? "rounded-br-md bg-brand text-brand-ink shadow-soft"
                  : "rounded-bl-md border border-line bg-surface-2 text-ink"}`}>
                  {msg.image && <img src={msg.image} alt="Photo you sent" className="mb-2 max-h-60 rounded-lg" />}
                  {isUser
                    ? <p className="whitespace-pre-wrap break-words">{msg.text}</p>
                    : <MessageText text={sanitizeMessageText(msg.text)} />}

                  {!isUser && Array.isArray(msg.citations) && msg.citations.length > 0 && (
                    <div className="mt-3 border-t border-line pt-3">
                      <p className="text-xs font-semibold text-muted">Sources</p>
                      <ol className="mt-1.5 space-y-1.5 text-xs text-muted">
                        {msg.citations.map((citation, idx) => (
                          <li key={`${citation.title || "source"}-${idx}`}>
                            <span className="font-medium text-ink">
                              {citation.index ? `[${citation.index}] ` : ""}{citation.title || "Clinical reference"}
                            </span>
                            {citation.source && <span> · {citation.source}</span>}
                          </li>
                        ))}
                      </ol>
                    </div>
                  )}

                  {!isUser && (
                    <div className="mt-3 flex items-center gap-1 border-t border-line pt-2 text-xs text-muted">
                      <span key={msg.feedback || "ask"} className="fade-in mr-1">{msg.feedback ? "Thanks for the feedback" : "Was this helpful?"}</span>
                      <button
                        onClick={() => handleFeedback(i, "up")}
                        className={`rounded-md p-1.5 transition-transform hover:bg-surface active:scale-90 ${msg.feedback === "up" ? "scale-110 text-ok" : ""}`}
                        aria-label="Helpful"
                        aria-pressed={msg.feedback === "up"}
                      >
                        <ThumbUp className="h-4 w-4" />
                      </button>
                      <button
                        onClick={() => handleFeedback(i, "down")}
                        className={`rounded-md p-1.5 transition-transform hover:bg-surface active:scale-90 ${msg.feedback === "down" ? "scale-110 text-danger" : ""}`}
                        aria-label="Not helpful"
                        aria-pressed={msg.feedback === "down"}
                      >
                        <ThumbDown className="h-4 w-4" />
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })}

          {isTyping && (
            <div className="message-in flex justify-start" role="status">
              <div className="flex items-center gap-3 rounded-2xl rounded-bl-md border border-line bg-surface-2 px-4 py-3 text-sm text-muted">
                <span className="flex gap-1" aria-hidden="true">
                  <span className="typing-dot h-1.5 w-1.5 rounded-full bg-brand" />
                  <span className="typing-dot h-1.5 w-1.5 rounded-full bg-brand" />
                  <span className="typing-dot h-1.5 w-1.5 rounded-full bg-brand" />
                </span>
                <span key={stepLabel} className="fade-in">{stepLabel || "Thinking"}</span>
              </div>
            </div>
          )}

          {pendingReview && !isTyping && (
            <p className="notice notice-warn fade-in">A clinician is checking your assessment. It will appear here once it is approved.</p>
          )}
        </div>

        {error && <p className="notice notice-danger fade-in mx-4 mb-3" role="alert">{error}</p>}

        {/* Composer, or what comes after a finished consultation */}
        {sessionClosed ? (
          <div className="fade-in space-y-3 border-t border-line px-4 py-4 sm:px-6">
            <p className="flex items-center gap-2 text-sm text-muted"><Check className="h-4 w-4 text-ok" /> This consultation is finished.</p>
            <div className="flex flex-wrap items-center gap-3">
              <button onClick={startNewConsultation} className="btn btn-primary"><Refresh className="h-4 w-4" /> Start a new consultation</button>
              {canAskFollowUp && followUpState !== "scheduled" && (
                <button onClick={requestFollowUp} disabled={followUpState === "saving"} className="btn btn-secondary">
                  {followUpState === "failed" ? "Could not schedule. Try again" : "Email me a check-in in 2 days"}
                </button>
              )}
              {followUpState === "scheduled" && (
                <span className="text-sm text-ok">Check-in scheduled. We will email {user.email} in 2 days.</span>
              )}
            </div>
          </div>
        ) : (
          <div className="border-t border-line px-4 py-3 sm:px-6">
            {imagePreview && (
              <div className="fade-in relative mb-3 inline-block">
                <img src={imagePreview} alt="Photo to send" className="h-20 w-20 rounded-lg border border-line object-cover" />
                <button
                  onClick={removeImage}
                  className="absolute -right-2 -top-2 flex h-6 w-6 items-center justify-center rounded-full border border-line bg-surface text-ink shadow-soft"
                  aria-label="Remove photo"
                >
                  <Close className="h-3.5 w-3.5" />
                </button>
              </div>
            )}

            <div className="flex items-end gap-2">
              <input type="file" ref={fileInputRef} onChange={handleImageChange} accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" />
              <button onClick={() => fileInputRef.current?.click()} className="btn btn-ghost px-2.5" aria-label="Add a photo" title="Add a photo">
                <Camera />
              </button>
              <textarea
                ref={inputRef}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Describe your symptoms"
                rows={Math.min(5, Math.max(1, input.split("\n").length))}
                className="input max-h-40 flex-1 resize-none"
                disabled={isTyping || pendingReview || !hasConsented}
                aria-label="Message"
              />
              <button
                onClick={sendMessage}
                disabled={isTyping || pendingReview || (!input.trim() && !image)}
                className="btn btn-primary px-3"
                aria-label="Send"
              >
                {isTyping ? <Spinner className="h-5 w-5" /> : <Send />}
              </button>
            </div>

            <p className="mt-2 text-xs text-muted">Enter to send, Shift and Enter for a new line. For emergencies, call your local emergency number.</p>
          </div>
        )}

        {/* Terms the user accepts before the first message */}
        {!hasConsented && (
          <div className="backdrop-in absolute inset-0 z-10 flex items-center justify-center overflow-y-auto bg-bg/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="consent-title">
            <div className="modal-in w-full max-w-md rounded-2xl border border-line bg-surface p-6 shadow-float">
              <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-soft text-brand"><Shield /></span>
              <h2 id="consent-title" className="mt-4 text-lg font-semibold text-ink">Before you start</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted">
                By continuing you agree to MedNexus processing the health information you share here, in line with India's DPDP Act, 2023.
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-relaxed text-ink">
                <li>This is an AI assistant. It is <strong>not a registered medical practitioner</strong> and cannot diagnose or prescribe.</li>
                <li>Your messages are processed to answer you and are stored encrypted.</li>
                <li>You will talk to a medical professional before taking any medicine.</li>
              </ul>
              <button onClick={() => setIsLegalOpen(true)} className="mt-3 text-sm font-medium text-brand hover:underline">
                Read the full terms and privacy notice
              </button>
              <div className="mt-6 flex gap-3">
                <Link to="/consultation" className="btn btn-secondary flex-1">Go back</Link>
                <button onClick={giveConsent} className="btn btn-primary flex-1">I understand and agree</button>
              </div>
            </div>
          </div>
        )}

        <LegalModal isOpen={isLegalOpen} onClose={() => setIsLegalOpen(false)} />
      </div>

      {/* Details, wide screens */}
      <aside className="stagger hidden w-72 shrink-0 flex-col gap-4 overflow-y-auto xl:flex" aria-label="About this consultation">
        <div className="card p-5" style={{ "--i": 1 }}>
          <p className="section-title">This consultation</p>
          <p className={`mt-3 flex items-center gap-2 text-sm font-medium ${status.tone}`}>
            <span className={`h-2 w-2 rounded-full bg-current ${status.label === "In progress" ? "pulse-ring" : ""}`} /> {status.label}
          </p>
          <dl className="mt-4 space-y-2.5 text-sm">
            {context.map((row) => (
              <div key={row.label} className="flex items-center justify-between gap-3">
                <dt className="text-muted">{row.label}</dt>
                <dd className="font-medium text-ink">
                  {row.to ? <Link to={row.to} className="hover:text-brand hover:underline">{row.value}</Link> : row.value}
                </dd>
              </div>
            ))}
          </dl>
          <div className="mt-4">
            <div className="flex justify-between text-xs text-muted">
              <span>{user?.isGuest ? "Guest usage today" : "Usage"}</span>
              <span className="tabular-nums">{usagePercent}%</span>
            </div>
            <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-surface-2">
              <div className="h-full rounded-full bg-brand transition-[width] duration-700 ease-out" style={{ width: `${usagePercent}%` }} />
            </div>
          </div>
        </div>

        <div className="card space-y-2 p-5" style={{ "--i": 2 }}>
          <p className="section-title mb-3">Actions</p>
          <button onClick={finishConsultation} disabled={!canFinish} className="btn btn-secondary w-full">Finish and get summary</button>
          <button onClick={startNewConsultation} disabled={messages.length === 0 || isTyping} className="btn btn-ghost w-full">Start over</button>
          {!canFinish && !sessionClosed && !pendingReview && (
            <p className="text-xs leading-relaxed text-muted">You can ask for the summary after answering two questions.</p>
          )}
        </div>

        <div className="notice notice-warn" style={{ "--i": 3 }}>
          <p className="font-semibold">In an emergency</p>
          <p className="mt-1">Do not wait for a reply here. Call your local emergency number or go to the nearest hospital.</p>
        </div>
      </aside>
    </div>
  );
}
