import os
import sys
import unittest

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "agents")))

from safety_oversight import verify_response


class SafetyOversightTests(unittest.TestCase):
    def test_replaces_unsafe_dosage_recommendation(self):
        result = verify_response(
            ai_response="Take metformin 500 mg twice daily and increase to 1000 mg if needed.",
            retrieved_context="",
            user_query="What should I take for diabetes?",
            urgency="routine",
        )
        self.assertFalse(result["is_safe"])
        self.assertIn("unsafe", result["modified_response"].lower())
        self.assertNotIn("metformin 500 mg twice daily", result["modified_response"].lower())

    def test_appends_mandatory_warning_for_chest_pain(self):
        result = verify_response(
            ai_response="You should rest and monitor your symptoms.",
            retrieved_context="",
            user_query="I have chest pain",
            urgency="emergency",
        )
        self.assertTrue(result["warnings_added"])
        self.assertIn("emergency", result["modified_response"].lower())

    def test_blocks_sensitive_output(self):
        result = verify_response(
            ai_response="John Doe's SSN is 123-45-6789.",
            retrieved_context="",
            user_query="Can you verify identity?",
            urgency="routine",
        )
        self.assertFalse(result["is_safe"])
        self.assertIn("privacy-violating", result["modified_response"].lower())

    def test_strips_duplicate_legal_footer_and_internal_labels(self):
        noisy_response = (
            "Take rest and monitor your symptoms.\n\n"
            "⚖️ MEDICAL LEGAL DISCLAIMER\n"
            "This response is generated by an AI assistant for educational and informational purposes only.\n"
            "VERIFIED SOURCES 3\n"
            "LATENCY: 12ms\n"
            "ACCURATE?\n"
            "⚖️ MEDICAL LEGAL DISCLAIMER\n"
        )

        result = verify_response(
            ai_response=noisy_response,
            retrieved_context="",
            user_query="I feel unwell",
            urgency="routine",
        )

        self.assertEqual(result["modified_response"].count("MEDICAL LEGAL DISCLAIMER"), 1)
        self.assertNotIn("VERIFIED SOURCES", result["modified_response"])
        self.assertNotIn("LATENCY:", result["modified_response"])
        self.assertNotIn("ACCURATE?", result["modified_response"])


if __name__ == "__main__":
    unittest.main()
