"""
Aether Clinic — Safety Oversight Agent
========================================
Cross-checks the AI's final response against retrieved medical protocols
to detect potential hallucinations, dangerous advice, or missing safety warnings.

Acts as the final "gate" before the response reaches the user.
"""

import re
import unicodedata

# =============================
# Safety Rule Sets
# =============================

# Red flag patterns that MUST be in the response if the context mentions them
MANDATORY_WARNINGS = {
    "dengue": {
        "check_for": ["aspirin", "ibuprofen", "nsaid", "bleeding risk"],
        "warning": "⚠️ SAFETY: Dengue patients must NOT take Aspirin or Ibuprofen. Only Paracetamol is safe."
    },
    "anaphylaxis": {
        "check_for": ["epinephrine", "epipen", "emergency", "911"],
        "warning": "⚠️ SAFETY: Anaphylaxis requires IMMEDIATE epinephrine and emergency services."
    },
    "suicidal": {
        "check_for": ["crisis", "helpline", "988", "emergency"],
        "warning": "⚠️ SAFETY: If you or someone you know is in crisis, please call 988 (US) or your local emergency services immediately."
    },
    "chest pain": {
        "check_for": ["emergency", "911", "cardiac", "aspirin"],
        "warning": "⚠️ SAFETY: Unexplained chest pain should be treated as a potential cardiac event. Seek immediate emergency care."
    },
    "dka": {
        "check_for": ["emergency", "hospital", "immediate"],
        "warning": "⚠️ SAFETY: Diabetic Ketoacidosis (DKA) is life-threatening and requires IMMEDIATE emergency medical care."
    },
    "thunderclap headache": {
        "check_for": ["emergency", "hemorrhage", "immediate"],
        "warning": "⚠️ SAFETY: A sudden severe 'thunderclap' headache requires IMMEDIATE emergency evaluation."
    }
}

# Things the AI should NEVER say
FORBIDDEN_PATTERNS = [
    r"i\s+diagnose\s+you\s+with",
    r"you\s+have\s+(been\s+diagnosed|a\s+confirmed)",
    r"take\s+\d+\s*mg\s+of",
    r"prescription\s+for",
    r"i\s+prescribe",
    r"you\s+definitely\s+have",
    r"this\s+is\s+(certainly|definitely)\s+",
    r"you\s+must\s+take\s+(this\s+)?medic",
]

# Unsafe output patterns that should be caught even when phrased indirectly.
DANGEROUS_OUTPUT_PATTERNS = [
    r"\bhow\s+to\s+mix\b.*\b(chemical|chemicals|acid|bleach|gasoline|poison|sulfur|sulphur)\b",
    r"\bstep[-\s]?by[-\s]?step\b.*\b(bomb|weapon|explosive|firearm|detonate|ignite)\b",
    r"\b(recipe|instructions|process)\b.*\b(dangerous|unsafe|deadly)\b",
]

# Response-side PII leakage patterns.
PII_OUTPUT_PATTERNS = [
    r"\b\d{3}-\d{2}-\d{4}\b",  # SSN
    r"\b(?:\d[ -]*?){13,16}\b",  # Credit card style sequence
    r"\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b",  # Phone number
]

# Drug names that should not be recommended with specific dosages
RESTRICTED_RECOMMENDATIONS = [
    "metformin", "atorvastatin", "lisinopril", "amlodipine",
    "warfarin", "heparin", "insulin", "prednisone", "amoxicillin",
    "ciprofloxacin", "azithromycin", "omeprazole", "metoprolol"
]


# =============================
# Legal & Compliance
# =============================
MANDATORY_FOOTER = (
    "\n\n" + "━" * 40 + "\n"
    "⚖️ MEDICAL LEGAL DISCLAIMER\n"
    "━" * 40 + "\n"
    "This response is generated by an AI assistant for educational and informational purposes only. "
    "It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
    "Always seek the advice of your physician or other qualified health provider with any questions "
    "you may have regarding a medical condition. Never disregard professional medical advice or "
    "delay in seeking it because of something you have read here.\n"
    "IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, CALL YOUR LOCAL EMERGENCY SERVICES (e.g., 911 in US, 102 in India) IMMEDIATELY."
)

ZERO_WIDTH_RE = re.compile(r"[\u200B-\u200D\uFEFF]")
DISCLAIMER_BLOCK_RE = re.compile(
    r"(?:\n\s*[━─-]{3,}\s*\n\s*⚖️?\s*MEDICAL LEGAL DISCLAIMER.*?"
    r"(?:IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, CALL YOUR LOCAL EMERGENCY SERVICES.*?|"
    r"IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, CALL EMERGENCY SERVICES.*?))"
    r"(?=\n\s*[━─-]{3,}\s*\n|\Z)",
    re.IGNORECASE | re.DOTALL,
)
INTERNAL_METADATA_LINE_RE = re.compile(
    r"^\s*(VERIFIED SOURCES.*|ACCURATE\?|LATENCY:.*|UPTIME:.*|AETHER CLINIC v.*|BUILD:.*|CORE:.*|IDENTITY:.*|TOKENS?:.*|SECURE LINK ESTABLISHED.*|NEURAL LINK ACTIVE.*|\[\s*EXECUTE\s*\])\s*$",
    re.IGNORECASE,
)
DISCLAIMER_LINE_RE = re.compile(
    r"^\s*(?:⚖️\s*)?(?:MEDICAL LEGAL DISCLAIMER|"
    r"This response is generated by an AI assistant for educational(?: and informational)? purposes only\.?|"
    r"It is NOT a substitute for professional medical advice(?:, diagnosis, or treatment)?\.?|"
    r"Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition\.?|"
    r"Always consult a physician\.?|"
    r"Never disregard professional medical advice or delay in seeking it because of something you have read here\.?|"
    r"IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, CALL (?:YOUR LOCAL )?EMERGENCY SERVICES.*?IMMEDIATELY\.?)\s*$",
    re.IGNORECASE,
)


def _normalize_text(text: str) -> str:
    normalized = unicodedata.normalize("NFKC", text or "")
    normalized = ZERO_WIDTH_RE.sub("", normalized)
    normalized = normalized.lower()
    normalized = re.sub(r"[-_/|]", " ", normalized)
    normalized = re.sub(r"[^\w\s]", " ", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


def _contains_any(text: str, terms: list[str]) -> bool:
    return any(term in text for term in terms)


def _strip_internal_artifacts(text: str) -> str:
    if not text:
        return ""

    cleaned = DISCLAIMER_BLOCK_RE.sub("", text)
    cleaned_lines = []

    for line in cleaned.splitlines():
        if INTERNAL_METADATA_LINE_RE.match(line):
            continue
        if DISCLAIMER_LINE_RE.match(line):
            continue
        cleaned_lines.append(line)

    cleaned = "\n".join(cleaned_lines)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()


def verify_response(
    ai_response: str,
    retrieved_context: str,
    user_query: str,
    urgency: str = "routine",
    feedback_examples: list = None
) -> dict:
    """
    Verifies an AI response against safety rules, retrieved medical protocols,
    and past negative feedback (Flywheel).

    Args:
        ai_response: The AI-generated response text
        retrieved_context: The medical protocol context that was fed to the AI
        user_query: The original user query
        urgency: Urgency level from Triage Classifier
        feedback_examples: List of past 'Thumbs Down' cases to avoid repeating mistakes
    """
    response_lower = ai_response.lower()
    response_normalized = _normalize_text(ai_response)
    query_lower = user_query.lower()
    query_normalized = _normalize_text(user_query)
    context_lower = (retrieved_context or "").lower()
    context_normalized = _normalize_text(retrieved_context or "")

    warnings_added = []
    violations_found = []
    modified_response = _strip_internal_artifacts(ai_response)

    # === CHECK 0: Feedback Flywheel (Learn from past mistakes) ===
    if feedback_examples:
        for ex in feedback_examples:
            ex_resp_norm = _normalize_text(ex.get("aiResponse", ""))
            # Simple substring match or high overlap check for V1
            # In V2, we would use semantic similarity (embeddings)
            if ex_resp_norm and ex_resp_norm in response_normalized:
                violations_found.append(f"Feedback Flywheel: This response style was previously flagged as unsafe.")
                break

    # === CHECK 1: Forbidden Patterns ===
    for pattern in FORBIDDEN_PATTERNS:
        if re.search(pattern, response_lower) or re.search(pattern, response_normalized):
            violations_found.append(f"Forbidden pattern detected: '{pattern}'")

    # === CHECK 2: Prescription Drug Dosage Check ===
    for drug in RESTRICTED_RECOMMENDATIONS:
        # Check if the AI is recommending a specific dosage of a prescription drug
        dosage_pattern = rf"{drug}\s*\d+\s*(mg|ml|mcg|units|tablet|tablets|capsule|capsules)"
        if re.search(dosage_pattern, response_lower) or re.search(dosage_pattern, response_normalized):
            violations_found.append(f"Specific dosage recommendation for prescription drug: {drug}")

    # === CHECK 2b: Dangerous instructions or PII in output ===
    for pattern in DANGEROUS_OUTPUT_PATTERNS + PII_OUTPUT_PATTERNS:
        if re.search(pattern, response_lower) or re.search(pattern, response_normalized):
            violations_found.append(f"Unsafe output detected: '{pattern}'")

    # === CHECK 3: Mandatory Warnings ===
    for trigger, rule in MANDATORY_WARNINGS.items():
        # Check if the trigger topic is relevant (in query or context)
        if trigger in query_lower or trigger in query_normalized or trigger in context_lower or trigger in context_normalized:
            # Check if the AI included the mandatory safety info
            has_safety_content = any(
                check_word in response_lower
                for check_word in rule["check_for"]
            )

            if not has_safety_content:
                warnings_added.append(rule["warning"])

    # === CHECK 4: Emergency Response Verification ===
    if urgency == "emergency":
        emergency_phrases = ["emergency", "911", "102", "108", "hospital", "immediate"]
        has_emergency_direction = any(phrase in response_lower for phrase in emergency_phrases)

        if not has_emergency_direction:
            warnings_added.append(
                "🚨 EMERGENCY ALERT: Based on your symptoms, please seek IMMEDIATE emergency medical care. "
                "Call emergency services (e.g., 102 or 108 in India, 911 in US) or go to the nearest emergency room."
            )

    # === APPLY MODIFICATIONS ===
    if violations_found:
        modified_response = (
            "I can’t help with unsafe, harmful, or privacy-violating requests. "
            "Please ask for general medical guidance, symptom triage, or emergency next steps."
        )
    else:
        modified_response = _strip_internal_artifacts(ai_response)

    # Guard against cumulative growth: 
    # If the response already seems to have a safety block, don't add more dividers
    safety_block_pattern = r"(🛡️ SAFETY OVERSIGHT|⚖️ MEDICAL LEGAL DISCLAIMER)"
    has_existing_safety = re.search(safety_block_pattern, modified_response, re.IGNORECASE)

    safety_additions = ""

    # 1. Add specific warnings if triggered
    if warnings_added:
        if not has_existing_safety:
            safety_additions += "\n\n---\n🛡️ SAFETY OVERSIGHT SYSTEM\n---\n"
        else:
            safety_additions += "\n\n"
        safety_additions += "\n".join(warnings_added)

    # 2. Add the legal disclaimer footer only IF NOT PRESENT (Case-Insensitive)
    disclaimer_marker = "MEDICAL LEGAL DISCLAIMER"
    if disclaimer_marker.lower() not in modified_response.lower():
        if not safety_additions and not has_existing_safety:
             safety_additions += "\n\n---\n"
        else:
             safety_additions += "\n\n"
             
        # Use a cleaner, symbol-free footer to avoid LLM tokens looping
        safety_additions += (
            f"⚖️ {disclaimer_marker}\n"
            "This response is generated by an AI assistant for educational purposes only. "
            "It is NOT a substitute for professional medical advice. Always consult a physician. "
            "IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, CALL EMERGENCY SERVICES (911/102/108) IMMEDIATELY."
        )

    modified_response += safety_additions
    modified_response = re.sub(r"\n{3,}", "\n\n", modified_response).strip()

    # === CALCULATE SAFETY SCORE ===
    # Start at 1.0, deduct for violations
    safety_score = 1.0
    safety_score -= len(violations_found) * 0.15
    safety_score -= len(warnings_added) * 0.05  # Warnings are less severe (we fix them)
    safety_score = max(0.0, min(1.0, safety_score))

    return {
        "is_safe": len(violations_found) == 0,
        "modified_response": modified_response,
        "warnings_added": warnings_added,
        "violations_found": violations_found,
        "safety_score": round(safety_score, 2)
    }
